export const FETCH_POPULAR_PREVIEW = 'FETCH_POPULAR_PREVIEW';
export const FETCH_UPCOMING_PREVIEW = 'FETCH_UPCOMING_PREVIEW';

export const FETCH_POPULAR_MOVIES = 'FETCH_POPULAR_MOVIES';
export const FETCH_UPCOMING_MOVIES = 'FETCH_UPCOMING_MOVIES'; 

export const FETCH_MOVIE_INFO = 'FETCH_MOVIE_INFO';

export const FETCH_SEARCH_MOVIE = 'FETCH_SEARCH_MOVIE';

export const ADD_VIEWED_MOVIES = 'ADD_VIEWED_MOVIES'; 

export const SHOW_LOADER = 'SHOW_LOADER';
export const HIDE_LOADER = 'HIDE_LOADER';